### ISSUE TITLE
Plugin doesn't work with latest google-api-client versions 0.11.*

### ISSUE THREAD

**Issue by xaduha** [treasure-data/embulk-input-google_analytics#24]
Works when installing google-api-client 0.10.3 manually, before embulk-input-google_analytics.

Also embulk-input-google_analytics v0.1.13 isn't available on rubygems.

**Comment by sakama** [comment]
Thanks.
First, I released v0.1.13 to [RubyGems.org](https://rubygems.org/gems/embulk-input-google_analytics/versions/0.1.13)

> Plugin doesn't work with latest google-api-client versions 0.11.*

I confirmed `rake` failed with google-api-client v0.11.*
I'll send PR to fix this problem.

**Comment by sakama** [comment]
build failure will be fixed at #26. Thanks!
